version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
    env_file:
      - .env
  web:
    restart: always
    build: .
    command: >
      bash -c "python ./bash/prepare.py
      && ./bash/wrapper.sh"
    volumes:
      - .:/news
    ports:
      - 80:8888
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data: